### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AlimuddinSodel** [iamageo/AnotherReadMoreLibrary#35]
FATAL EXCEPTION: 
java.lang.StringIndexOutOfBoundsException: begin 0, end 178, length 176
at java.lang.String.checkBoundsBeginEnd(String.java:3942)
at java.lang.String.substring(String.java:2467)

**Comment by iamageo** [comment]
Heelo @AlimuddinSodel ,thanks for your issue, I'm analyzing the error sent and I'll be back soon with updates.

**Comment by AlimuddinSodel** [comment]
@iamageo did you fix the issue?

**Comment by iamageo** [comment]
Hello @AlimuddinSodel, I couldn't reproduce the specified error, can you give me details of your implementation?

**Comment by AlimuddinSodel** [comment]
Try to scroll recyclerView continuously

**Comment by iamageo** [comment]
try again using new version 1.0.2

See: 

Fix https://github.com/iamageo/AnotherReadMoreLibrary/issues/35

Full Changelog: https://github.com/iamageo/AnotherReadMoreLibrary/compare/1.0.1...1.0.2

**Comment by AlimuddinSodel** [comment]
Thanks man. its working now

**Comment by iamageo** [comment]
Thanks for your contributing! ✨
