### ISSUE TITLE
Remoe underline & color chnage of More,Less label

### ISSUE THREAD

**Issue by preetykaushik1012** [iamageo/AnotherReadMoreLibrary#38]
Remoe underline & color change of More,Less label (Format)

**Comment by iamageo** [comment]
Hello @preetykaushik1012 , see last version of another read more:

Updates:

- now we can control the label color with `moreLabelColor` and `lessLabelColor`
- control underline visibility with `underlineVisible`

[Release 1.0.3](https://github.com/iamageo/AnotherReadMoreLibrary/releases/tag/1.0.3)
